### ISSUE TITLE
docs.docker-cn.com 请问这个网站是 Docker 官方和阿里云合办的吗？

### ISSUE THREAD

**Issue by khs1994** [allencloud/docker-changelog-chinese#13]

**Comment by allencloud** [comment]
I am really sorry, and I have no idea about this. 
While it seems that https://docs.docker-cn.com has not been updated for a long time.

**Comment by khs1994** [comment]
感谢，但网站 IP 指向的 阿里云 香港服务器。

**Comment by allencloud** [comment]
Currently I work on project [pouch](https://github.com/alibaba/pouch).
You can go there for hacking fun, if you are interested.
